sudo: required
dist: trusty

language: python
python:
- '2.7'

env:
  matrix:
  - ANSIBLE_REF=devel
  - ANSIBLE_REF=stable-2.1

install:
- travis_retry wget https://raw.githubusercontent.com/novafloss/ansible-setup/rewrite/ansible-setup
- bash ansible-setup ansible_ref_require $ANSIBLE_REF /usr/bin
- bash ansible-setup lxd_require

script:
- sg lxd 'ansible-playbook -v test.yml'
