sudo: required
dist: trusty

language: python
python:
- '3.5'

env:
  matrix:
  - ANSIBLE_REF=devel
  - ANSIBLE_REF=stable-2.1

install:
- travis_retry curl https://raw.githubusercontent.com/novafloss/ansible-setup/4640060e9770de86b2f985dacec8fc13a88e521c/ansible-setup
- bash ansible-setup ansible_ref_require $ANSIBLE_REF /usr/bin
- bash ansible-setup lxd_require

script:
- sg lxd 'ansible-playbook -v test.yml'
